---
- name: Upgrade packages
  apt:
    upgrade: safe
    update_cache: true
    cache_valid_time: 300

- name: Install packages
  apt:
    name:
      - aptitude
      - acl
      - at
      - ca-certificates
      - jq
      - curl
      - git-core
      - gnupg
      - lsb-release
      - python3-pymysql
      - rsync
      - unzip
    state: present
    update_cache: true
